<?php

/**
   * @file
   *  This module is for testing purposes.
   */


  /**
   * Implements hook_form_FORM_ID_alter.
   */
   function training_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    //kint($form);die('Exiting');
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.
  // Add a checkbox to registration form about agreeing to terms of use.
    $form['custom_training_field'] = [
      '#type' => 'textfield',
      '#title' => t('Custom Training Field'),
      '#required' => TRUE,
      '#description' => t('This is sample field for description.'),
      '#default_value' => t('Please enter a default value.'),
    ];
    $entity_manager = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load(12);
            //$node = $entity_manager->getStorage('node')->load(5);             
          //  print_r($node);exit;
    kint($entity_manager);die;
    $training_service = \Drupal::service('training.node_json');
    kint($training_service->getNode(5));die;
    
  /*$form['terms_of_use'] = [
    '#type' => 'checkbox',
    '#title' => t("I agree with the website's terms and conditions."),
    '#required' => TRUE,
  ];*/
}
   
function training_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {  
//print $hook;
}

function training_preprocess_node(&$vars) {
  $vars['hello_training'] = t('This variable is created from Preprocess.');
}

